title: metabismuth
description: >-
  Cool
baseurl: "" # e.g. /blog
url: "http://metabismuth.github.io" # e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  posts:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: _posts
    values:
      layout: post

sass:
    sass_dir: asset/_cool
